// <auto-generated />
using System;
using Base2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Base2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224161233_AddVersioningAndChangeLog")]
    partial class AddVersioningAndChangeLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Base2.Models.DutyAssignment", b =>
                {
                    b.Property<int>("DutyAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AmmoCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmmoType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DutySectionNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WeaponId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DutyAssignmentId");

                    b.HasIndex("DutySectionNodeId");

                    b.HasIndex("PersonId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("WeaponId");

                    b.ToTable("DutyAssignments");
                });

            modelBuilder.Entity("Base2.Models.DutyOrder", b =>
                {
                    b.Property<int>("DutyOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommanderInfo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceTemplateVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("DutyOrderId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("SourceTemplateId");

                    b.ToTable("DutyOrders");
                });

            modelBuilder.Entity("Base2.Models.DutySectionNode", b =>
                {
                    b.Property<int>("DutySectionNodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DutyOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DutyPositionTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DutyTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DutyTimeRangeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAmmo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasVehicle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasWeapon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAssignments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentDutySectionNodeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeRangeLabel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("DutySectionNodeId");

                    b.HasIndex("DutyOrderId");

                    b.HasIndex("DutyTemplateId");

                    b.HasIndex("DutyTimeRangeId");

                    b.HasIndex("ParentDutySectionNodeId");

                    b.HasIndex("ParentDutySectionNodeId", "OrderIndex");

                    b.ToTable("DutySectionNodes");
                });

            modelBuilder.Entity("Base2.Models.DutyTemplate", b =>
                {
                    b.Property<int>("DutyTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("DutyTemplateId");

                    b.ToTable("DutyTemplates");
                });

            modelBuilder.Entity("Base2.Models.DutyTimeRange", b =>
                {
                    b.Property<int>("DutyTimeRangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DutyOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.HasKey("DutyTimeRangeId");

                    b.HasIndex("DutyOrderId");

                    b.ToTable("DutyTimeRanges");
                });

            modelBuilder.Entity("Base2.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Base2.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Initials")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RankId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PersonId");

                    b.HasIndex("LastName");

                    b.HasIndex("PositionId");

                    b.HasIndex("RankId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Base2.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("PositionId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Base2.Models.Rank", b =>
                {
                    b.Property<int>("RankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RankLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("RankId");

                    b.HasIndex("RankName")
                        .IsUnique();

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("Base2.Models.TemplateChangeLog", b =>
                {
                    b.Property<int>("TemplateChangeLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChangeDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("DutyTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("TemplateChangeLogId");

                    b.HasIndex("DutyTemplateId");

                    b.HasIndex("DutyTemplateId", "Version");

                    b.ToTable("TemplateChangeLogs");
                });

            modelBuilder.Entity("Base2.Models.TemplateNode", b =>
                {
                    b.Property<int>("TemplateNodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemSeparator")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresAmmo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresVehicle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresWeapon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Separator")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Terminator")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("TemplateNodeId");

                    b.HasIndex("NodeType")
                        .IsUnique();

                    b.ToTable("TemplateNodes");
                });

            modelBuilder.Entity("Base2.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("VehicleId");

                    b.HasIndex("VehicleNumber")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Base2.Models.Weapon", b =>
                {
                    b.Property<int>("WeaponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StoredInLocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WeaponNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("WeaponType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("WeaponId");

                    b.HasIndex("StoredInLocationId");

                    b.HasIndex("WeaponNumber")
                        .IsUnique();

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("Base2.Models.DutyAssignment", b =>
                {
                    b.HasOne("Base2.Models.DutySectionNode", "DutySectionNode")
                        .WithMany("Assignments")
                        .HasForeignKey("DutySectionNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Base2.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Base2.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Base2.Models.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DutySectionNode");

                    b.Navigation("Person");

                    b.Navigation("Vehicle");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("Base2.Models.DutyOrder", b =>
                {
                    b.HasOne("Base2.Models.DutyTemplate", "SourceTemplate")
                        .WithMany("Orders")
                        .HasForeignKey("SourceTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceTemplate");
                });

            modelBuilder.Entity("Base2.Models.DutySectionNode", b =>
                {
                    b.HasOne("Base2.Models.DutyOrder", "DutyOrder")
                        .WithMany("Sections")
                        .HasForeignKey("DutyOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Base2.Models.DutyTemplate", "DutyTemplate")
                        .WithMany("Sections")
                        .HasForeignKey("DutyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Base2.Models.DutyTimeRange", "DutyTimeRange")
                        .WithMany()
                        .HasForeignKey("DutyTimeRangeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Base2.Models.DutySectionNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentDutySectionNodeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DutyOrder");

                    b.Navigation("DutyTemplate");

                    b.Navigation("DutyTimeRange");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Base2.Models.DutyTimeRange", b =>
                {
                    b.HasOne("Base2.Models.DutyOrder", "DutyOrder")
                        .WithMany("TimeRanges")
                        .HasForeignKey("DutyOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DutyOrder");
                });

            modelBuilder.Entity("Base2.Models.Person", b =>
                {
                    b.HasOne("Base2.Models.Position", "Position")
                        .WithMany("People")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Base2.Models.Rank", "Rank")
                        .WithMany("People")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("Base2.Models.TemplateChangeLog", b =>
                {
                    b.HasOne("Base2.Models.DutyTemplate", "DutyTemplate")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("DutyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DutyTemplate");
                });

            modelBuilder.Entity("Base2.Models.Weapon", b =>
                {
                    b.HasOne("Base2.Models.Location", "StoredInLocation")
                        .WithMany("StoredWeapons")
                        .HasForeignKey("StoredInLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StoredInLocation");
                });

            modelBuilder.Entity("Base2.Models.DutyOrder", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("TimeRanges");
                });

            modelBuilder.Entity("Base2.Models.DutySectionNode", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("Base2.Models.DutyTemplate", b =>
                {
                    b.Navigation("ChangeLogs");

                    b.Navigation("Orders");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Base2.Models.Location", b =>
                {
                    b.Navigation("StoredWeapons");
                });

            modelBuilder.Entity("Base2.Models.Position", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("Base2.Models.Rank", b =>
                {
                    b.Navigation("People");
                });
#pragma warning restore 612, 618
        }
    }
}
